### ISSUE TITLE
java.lang.NoSuchMethodError: macroid.viewable.ListableListAdapter.addAll

### ISSUE THREAD

**Issue by dzadc** [macroid/macroid#59]
Hey there! I've been playing around with the macroid-starter project and had a NoSuchMethodError happen when trying to run it on one of our older devices (2.3.6). It ran fine on the 4.x devices I've tried. Here is the relevant log dump. 

```
I/Launcher(  367): onWindowFocusChanged(false)
D/dalvikvm(  120): GC_EXPLICIT freed <1K, 50% free 2714K/5379K, external 0K/0K, paused 69ms
I/GLThread(  367): onPause tid=10
I/dalvikvm( 4965): Could not find method scala.collection.Seq.$plus$colon, referenced from method macroid.UiThreading$class.runUi
W/dalvikvm( 4965): VFY: unable to resolve interface method 14186: Lscala/collection/Seq;.$plus$colon (Ljava/lang/Object;Lscala/collection/generic/CanBuildFrom;)Ljava/lang/Object;
D/dalvikvm( 4965): VFY: replacing opcode 0x72 at 0x0012
D/dalvikvm( 4965): VFY: dead code 0x0015-002e in Lmacroid/UiThreading$class;.runUi (Lmacroid/UiThreading;Lmacroid/Ui;Lmacroid/Ui;Lscala/collection/Seq;)Lscala/concurrent/Future;
W/dalvikvm( 4965): VFY: unable to find class referenced in signature (Lscala/util/Either;)
E/dalvikvm( 4965): Could not find class 'scala.util.Right', referenced from method macroid.TextTweaks$class.hint
W/dalvikvm( 4965): VFY: unable to resolve instanceof 3162 (Lscala/util/Right;) in Lmacroid/TextTweaks$class;
D/dalvikvm( 4965): VFY: replacing opcode 0x20 at 0x0006
D/dalvikvm( 4965): VFY: dead code 0x0008-005c in Lmacroid/TextTweaks$class;.hint (Lmacroid/TextTweaks;Lscala/util/Either;)Lmacroid/Tweak;
W/dalvikvm( 4965): VFY: unable to find class referenced in signature (Lscala/util/Either;)
E/dalvikvm( 4965): Could not find class 'scala.util.Right', referenced from method macroid.TextTweaks$class.text
W/dalvikvm( 4965): VFY: unable to resolve instanceof 3162 (Lscala/util/Right;) in Lmacroid/TextTweaks$class;
D/dalvikvm( 4965): VFY: replacing opcode 0x20 at 0x0006
D/dalvikvm( 4965): VFY: dead code 0x0008-005c in Lmacroid/TextTweaks$class;.text (Lmacroid/TextTweaks;Lscala/util/Either;)Lmacroid/Tweak;
I/dalvikvm( 4965): Could not find method scala.concurrent.Future$.sequence, referenced from method macroid.ProgressSnails$class.waitProgress
W/dalvikvm( 4965): VFY: unable to resolve virtual method 17209: Lscala/concurrent/Future$;.sequence (Lscala/collection/TraversableOnce;Lscala/collection/generic/CanBuildFrom;Lscala/concurrent/ExecutionContext;)Lscala/concurrent/Future;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x002a
D/dalvikvm( 4965): VFY: dead code 0x002d-0041 in Lmacroid/ProgressSnails$class;.waitProgress (Lmacroid/ProgressSnails;Lscala/collection/immutable/List;Lscala/concurrent/ExecutionContext;)Lmacroid/Snail;
W/dalvikvm( 4965): VFY: unable to find class referenced in signature (Lscala/util/Either;)
E/dalvikvm( 4965): Could not find class 'scala.util.Right', referenced from method macroid.ToastBuilding$class.toast
W/dalvikvm( 4965): VFY: unable to resolve instanceof 3162 (Lscala/util/Right;) in Lmacroid/ToastBuilding$class;
D/dalvikvm( 4965): VFY: replacing opcode 0x20 at 0x0009
D/dalvikvm(  120): GC_EXPLICIT freed <1K, 50% free 2714K/5379K, external 0K/0K, paused 50ms
D/dalvikvm( 4965): VFY: dead code 0x000b-005d in Lmacroid/ToastBuilding$class;.toast (Lmacroid/ToastBuilding;Lscala/util/Either;Lmacroid/AppContext;)Lmacroid/Ui;
I/dalvikvm( 4965): Could not find method macroid.Loaf$.andThen, referenced from method macroid.Loaf.andThen
W/dalvikvm( 4965): VFY: unable to resolve virtual method 9719: Lmacroid/Loaf$;.andThen (Lscala/Function1;)Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0004
D/dalvikvm( 4965): VFY: dead code 0x0007-0009 in Lmacroid/Loaf;.andThen (Lscala/Function1;)Lscala/Function1;
I/dalvikvm( 4965): Could not find method macroid.Loaf$.compose, referenced from method macroid.Loaf.compose
W/dalvikvm( 4965): VFY: unable to resolve virtual method 9722: Lmacroid/Loaf$;.compose (Lscala/Function1;)Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0004
D/dalvikvm( 4965): VFY: dead code 0x0007-0009 in Lmacroid/Loaf;.compose (Lscala/Function1;)Lscala/Function1;
I/dalvikvm( 4965): Could not find method com.example.macroid.starter.ColorString$.curried, referenced from method com.example.macroid.starter.ColorString.curried
W/dalvikvm( 4965): VFY: unable to resolve virtual method 7918: Lcom/example/macroid/starter/ColorString$;.curried ()Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0002
D/dalvikvm( 4965): VFY: dead code 0x0005-0006 in Lcom/example/macroid/starter/ColorString;.curried ()Lscala/Function1;
I/dalvikvm( 4965): Could not find method com.example.macroid.starter.ColorString$.tupled, referenced from method com.example.macroid.starter.ColorString.tupled
W/dalvikvm( 4965): VFY: unable to resolve virtual method 7921: Lcom/example/macroid/starter/ColorString$;.tupled ()Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0002
D/dalvikvm( 4965): VFY: dead code 0x0005-0006 in Lcom/example/macroid/starter/ColorString;.tupled ()Lscala/Function1;
I/Main thread(  367): onPause waiting for mPaused.
I/GLThread(  367): mPaused is now true tid=10
I/GLThread(  367): releasing EGL surface because paused tid=10
W/EglHelper(  367): destroySurface()  tid=10
I/ApplicationPackageManager( 4965): cscCountry is not German : TMB
I/dalvikvm( 4965): Could not find method macroid.AppContext$.andThen, referenced from method macroid.AppContext.andThen
W/dalvikvm( 4965): VFY: unable to resolve virtual method 8661: Lmacroid/AppContext$;.andThen (Lscala/Function1;)Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0004
D/dalvikvm( 4965): VFY: dead code 0x0007-0009 in Lmacroid/AppContext;.andThen (Lscala/Function1;)Lscala/Function1;
I/dalvikvm( 4965): Could not find method macroid.AppContext$.compose, referenced from method macroid.AppContext.compose
W/dalvikvm( 4965): VFY: unable to resolve virtual method 8664: Lmacroid/AppContext$;.compose (Lscala/Function1;)Lscala/Function1;
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x0004
D/dalvikvm( 4965): VFY: dead code 0x0007-0009 in Lmacroid/AppContext;.compose (Lscala/Function1;)Lscala/Function1;
I/dalvikvm( 4965): Could not find method macroid.viewable.ListableListAdapter.addAll, referenced from method macroid.viewable.ListableListAdapter.<init>
W/dalvikvm( 4965): VFY: unable to resolve virtual method 11057: Lmacroid/viewable/ListableListAdapter;.addAll ([Ljava/lang/Object;)V
D/dalvikvm( 4965): VFY: replacing opcode 0x6e at 0x002d
D/dalvikvm( 4965): VFY: dead code 0x0030-0030 in Lmacroid/viewable/ListableListAdapter;.<init> (Lscala/collection/Seq;Lmacroid/ActivityContext;Lmacroid/AppContext;Lmacroid/viewable/Listable;)V
D/AndroidRuntime( 4965): Shutting down VM
W/dalvikvm( 4965): threadid=1: thread exiting with uncaught exception (group=0x4001e578)
W/EglHelper(  367): finish() tid=10
E/AndroidRuntime( 4965): FATAL EXCEPTION: main
E/AndroidRuntime( 4965): java.lang.NoSuchMethodError: macroid.viewable.ListableListAdapter.addAll
E/AndroidRuntime( 4965): 	at macroid.viewable.ListableListAdapter.<init>(ListableListAdapter.scala:13)
E/AndroidRuntime( 4965): 	at macroid.viewable.Listable$class.listAdapter(Listable.scala:164)
E/AndroidRuntime( 4965): 	at macroid.viewable.ListableBuilder$$anon$13.listAdapter(Listable.scala:184)
E/AndroidRuntime( 4965): 	at macroid.viewable.Listable$class.listAdapterTweak(Listable.scala:168)
E/AndroidRuntime( 4965): 	at macroid.viewable.ListableBuilder$$anon$13.listAdapterTweak(Listable.scala:184)
E/AndroidRuntime( 4965): 	at com.example.macroid.starter.MainActivity.onCreate(MainActivity.scala:82)
E/AndroidRuntime( 4965): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread.access$1500(ActivityThread.java:117)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
E/AndroidRuntime( 4965): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4965): 	at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 4965): 	at android.app.ActivityThread.main(ActivityThread.java:3691)
E/AndroidRuntime( 4965): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4965): 	at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 4965): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
E/AndroidRuntime( 4965): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
E/AndroidRuntime( 4965): 	at dalvik.system.NativeStart.main(Native Method)
D/PowerManager(  175): acquire flags=0x1 tag=ActivityManager-Launch
E/        (  175): Dumpstate > /data/log/dumpstate_app_error
D/dalvikvm( 4965): GC_CONCURRENT freed 361K, 51% free 2818K/5639K, external
 ```

Hoping someone can provide insight into whats going wrong!

**Comment by pfn** [comment]
The same exact apk runs on your android 4.x devices?

**Comment by dzadc** [comment]
That is correct, just confirmed by installing the apk from android-bin manually

**Comment by pfn** [comment]
I don't know in that case, I have not encountered any problems with macroid
on android 2.x, but I haven't tried using ListableListAdapter

**Comment by stanch** [comment]
Hmm, that’s weird! I don’t have a `2.x` device around, but I can try running this in the emulator over the weekend.

**Comment by stilomatic** [comment]
Hello i got the same issue:  java.lang.NoSuchMethodError: No virtual method runUi(Lmacroid/Ui;)Lscala/concurrent/Future; in class Lmacroid/FullDsl$; or its super classes (declaration of 'macroid.FullDsl$' appears in /data/app/com.timeslot-2/base.apk)

i am running emulator with android 6.0

here there is my class:

class MainActivity extends Activity with Contexts[Activity] {
  var slots: List[SlotDO] = List(new SlotDO("uno", List()), new SlotDO("due",List()))

  def slotsListable = // (implicit ctx: ActivityContext, appCtx: AppContext) =
    Listable[SlotDO].tr {
      l[VerticalLinearLayout](
     // w[ImageView],
      w[TextView] <~ TextTweaks.large
    )
    }(slot ⇒ Transformer {
      // case img: ImageView ⇒ img <~ ImageTweaks.bitmap(new Bitmap())//user.media[0].publicId
      case txt: TextView ⇒ txt <~ text(slot.title)
    })

  var myListView = w[ListView]



  override def onCreate(savedInstanceState: Bundle) = {
    super.onCreate(savedInstanceState)
    // layout params
    val lps = lp[LinearLayout](MATCH_PARENT, WRAP_CONTENT, 1.0f)

    val tweak = slotsListable.listAdapterTweak(this.slots)


    def callBack(mslots:List[SlotDO]): Unit= {
      Log.w("timeslot","**** CALLBACK ******")
      this.runOnUiThread(new Runnable {
        override def run(): Unit = {
          slots = mslots
          runUi {
            myListView <~ slotsListable.listAdapterTweak(slots)
          }
          Log.w("timeslot","**** FERTIG ******")
        }
      })

    }

    val c = new Client("http://stilo-studio.com/colors.json", callBack)
    c.httpRequest

    val view = l[LinearLayout](
        w[TextView] <~ TextTweaks.large <~ text("Timeslot"),
        this.myListView
      ) <~ vertical

    this.setContentView(getUi(view))

  }

  override def onStart() = {
    super.onStart()
  }
}

**Comment by stilomatic** [comment]
with Nexus 5 emulator i don't have this issue but also i am not able to populate correctly the ListView...
Can you point me at what is wrong

Thanks

**Comment by stilomatic** [comment]
This happened also to me: Sometimes it's needed a clean and a new compiling.
