### ISSUE TITLE
Unable to use android libs in console

### ISSUE THREAD

**Issue by joprice** [macroid/macroid#65]
I was playing with the start project and writing a helper for defining colors:

```scala
package com.example.macroid

import android.graphics.Color

package object starter {
  implicit class HexStringContext(sc: StringContext) {
    def hex(): Int = Color.parseColor("#" + sc.parts.mkString)
  }

  hex"EC4908"
}

```

and I got the following error:

```
java.lang.NoClassDefFoundError: android/graphics/Color
  at com.example.macroid.starter.package$HexStringContext.hex(package.scala:7)
  at com.example.macroid.starter.package$.<init>(package.scala:10)
  at com.example.macroid.starter.package$.<clinit>(package.scala)
  ... 43 elided
Caused by: java.lang.ClassNotFoundException: android.graphics.Color
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 46 more
```

**Comment by pfn** [comment]
The android framework is not available in JVM.
